export default[
  {
    "login": "aman-singanamala",
    "id": 84006448,
    "node_id": "MDQ6VXNlcjg0MDA2NDQ4",
    "avatar_url": "https://avatars.githubusercontent.com/u/84006448?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/aman-singanamala",
    "html_url": "https://github.com/aman-singanamala",
    "followers_url": "https://api.github.com/users/aman-singanamala/followers",
    "following_url": "https://api.github.com/users/aman-singanamala/following{/other_user}",
    "gists_url": "https://api.github.com/users/aman-singanamala/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/aman-singanamala/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/aman-singanamala/subscriptions",
    "organizations_url": "https://api.github.com/users/aman-singanamala/orgs",
    "repos_url": "https://api.github.com/users/aman-singanamala/repos",
    "events_url": "https://api.github.com/users/aman-singanamala/events{/privacy}",
    "received_events_url": "https://api.github.com/users/aman-singanamala/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "SaurabhM04",
    "id": 88313164,
    "node_id": "MDQ6VXNlcjg4MzEzMTY0",
    "avatar_url": "https://avatars.githubusercontent.com/u/88313164?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/SaurabhM04",
    "html_url": "https://github.com/SaurabhM04",
    "followers_url": "https://api.github.com/users/SaurabhM04/followers",
    "following_url": "https://api.github.com/users/SaurabhM04/following{/other_user}",
    "gists_url": "https://api.github.com/users/SaurabhM04/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/SaurabhM04/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/SaurabhM04/subscriptions",
    "organizations_url": "https://api.github.com/users/SaurabhM04/orgs",
    "repos_url": "https://api.github.com/users/SaurabhM04/repos",
    "events_url": "https://api.github.com/users/SaurabhM04/events{/privacy}",
    "received_events_url": "https://api.github.com/users/SaurabhM04/received_events",
    "type": "User",
    "site_admin": false
  }
]
